<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZGxm0Qh\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZGxm0Qh/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerZGxm0Qh.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerZGxm0Qh\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerZGxm0Qh\appAppKernelProdContainer([
    'container.build_hash' => 'ZGxm0Qh',
    'container.build_id' => '636ba6c9',
    'container.build_time' => 1727445856,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZGxm0Qh');
