<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHoqg4nD\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHoqg4nD/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerHoqg4nD.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerHoqg4nD\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerHoqg4nD\appAppKernelProdContainer([
    'container.build_hash' => 'Hoqg4nD',
    'container.build_id' => '58e10889',
    'container.build_time' => 1727423150,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHoqg4nD');
