<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBx6mTAw\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBx6mTAw/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerBx6mTAw.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerBx6mTAw\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerBx6mTAw\appAppKernelProdContainer([
    'container.build_hash' => 'Bx6mTAw',
    'container.build_id' => 'b4cf4bf3',
    'container.build_time' => 1728372482,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBx6mTAw');
